name: Pre-Production-Cron
on:
    schedule:
      - cron: '0 16 * * *'
jobs:
    production:
        name: Pre-Production
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: ${{ matrix.python-version }}
          - name: Install packages
            run: |
              pip install python-dateutil
          - name: run daily cron
            run: |
                python3 main.py
            env:
              GSTALDERCONFIG: ${{ secrets.GSTALDERCONFIG_TEST }}
