name: Production-Cron
on:
  schedule:
    - cron: '0 18 * * *' # Runs at 18:00 UTC
  workflow_dispatch:  # Enables manual trigger

jobs:
  production:
    name: Production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  # Pin to a specific version of Python

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip  # Upgrade pip to the latest version

      - name: Install packages
        run: |
          source venv/bin/activate
          pip install python-dateutil requests   # Install your required dependencies

      - name: Run daily cron
        run: |
          source venv/bin/activate
          python3 main.py
        env:
          GSTALDERCONFIG: ${{ secrets.GSTALDERCONFIG_PROD }}  # Ensure the secret is set
