name: Tests
on: 
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: python srcs/return5.py -v
        run: python srcs/return5.py -v
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tox and any other packages
        run: pip install tox
      - name: Run tox
        run: tox -e py
        env:
          GSTALDERCONFIG: ${{ secrets.GSTALDERCONFIG }}
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  integration:
    name: Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: run
        run: |
          python3 srcs/main.py
        env:
          GSTALDERCONFIG: ${{ secrets.GSTALDERCONFIG }}